### ISSUE TITLE
SNT processing

### ISSUE THREAD

**Issue by thinkwee** [stangelid/qt#2]
Hi~ thank you for your great job!
I see in your code(qt.py), there is a preprocessing part:
```
sent_tokens = torch.ones(batch_size, nsent, 1).long() * self.unk_idx
sent_tokens = sent_tokens.to(device)

src = torch.cat([sent_tokens, src], dim=2)
```
does it means unk_idx equals to the [SNK] special token mentioned in the paper?

**Comment by stangelid** [comment]
Hi there,

Thanks for your interest in our work!

Yes, the `unk_idx` index corresponds to the [SNT] token, as you describe. We should have used a better naming (like `snt_idx`), but we missed this -- apologies!

**Comment by thinkwee** [comment]
got it, thx for your reply!
